- hosts: master01
  become: yes
  tasks:
    - name: daemon-reload
      shell: systemctl daemon-reload
    - name: restart kubelet
      service:
        name: kubelet
        state: restarted
    - name: initialize the cluster
      shell: kubeadm init --pod-network-cidr=10.244.0.0/16 --control-plane-endpoint=kube.box.org --upload-certs >> cluster.txt
    - name: create .kube directory
      become: yes
      become_user: admin
      file:
        path: $HOME/.kube
        state: directory
        mode: 0755
    - name: copy admin.conf to user's kube config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/admin/.kube/config
        remote_src: yes
        owner: admin
    - name: install Pod network
      become: yes
      become_user: admin
      shell: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
      args:
        chdir: $HOME
        creates: pod_network_setup.txt
